### PR TITLE
Remove unnecessary logging

### LINKED ISSUE #1645: Conflict between dash to panel and PopOS cosmic workspaces
**Describe the bug**
Waking the computer after suspend results in cosmic's workspace overview disappearing until the shell or computer is restarted. This is definitely an issue with dash to panel as it doesn't occur when using the default dock.

See the issue previously opened here. 13r0ck says the Pop Cosmic team encountered the same issue when upgrading to 22.04 ubuntu dock and mentioned I should bring up this issue with you as they can't resolve it from their end. They're open to working with you on solving it.
https://github.com/pop-os/cosmic-workspaces/issues/35#issuecomment-1095584310

**Software versions**
PopOS 21.10
Gnome 40.4.0
Gnome shell 40.5
Dash to Panel version 44

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
Normal view
https://user-images.githubusercontent.com/62437512/148533947-a5f258f2-94cd-4bc4-b2da-69e03f8749a2.png
After suspend
https://user-images.githubusercontent.com/62437512/148534128-b5a2aa89-d373-4fea-813a-ccb1059926b0.png

### PR DESCRIPTION
**Pull request by 13r0ck**
Load JS object in a way that doesn't result in workspace code
being printed to the system journal.

Fixes https://github.com/home-sweet-gnome/dash-to-panel/issues/1645#issuecomment-1112930912

### CODE REVIEW

File: workspacesView.js [hunk 1]
```diff
@@ -16,7 +16,9 @@ const Util = Self.imports.util;
 
 function override() {
     global.vertical_overview.GSFunctions['WorkspacesView'] = Util.overrideProto(WorkspacesView.WorkspacesView.prototype, WorkspacesViewOverride);
-    log('You may see an error below,\nSecondaryMonitorDisplay is defined as const for some reason.\nSecondaryMonitorDisplay = ' + WorkspacesView.SecondaryMonitorDisplay + '\nSince I\'m overriding values in that const an error show might show up.\n Feel free to ignore it');
+    log('You may see an error below,\nSecondaryMonitorDisplay is defined as const for some reason\nSince I\'m overriding values in that const an error show might show up.\n Feel free to ignore it');
```
Comment (leviport) [inline workspacesView.js]: >`an error show might show up`

Might as well fix that typo while you're at it, right?

Comment (13r0ck) [reply workspacesView.js:19]: What typo?. Feel free to just push a commit to this that fixes that

Comment (13r0ck) [reply workspacesView.js]: Oh, good eye! I had to re-read that 3 times to see the error lol

**Review by n3m0-22 — APPROVED** [review]
This makes a significant difference in the logs. Tested with and without dash-to-panel, and with and without an external display connected.

I was not able to recreate the issue with overview disappearing.

In regards to the issue https://github.com/home-sweet-gnome/dash-to-panel/issues/1645#issuecomment-1121187431, I was able to recreate this. If dash-to-panel is enabled go to Settings > Desktop > Dock and turn off  Enable Dock to fix the problem.

This looks good.

[without-less-logs.txt](https://github.com/pop-os/cosmic-workspaces/files/8848032/without-less-logs.txt)
[with-less-logs.txt](https://github.com/pop-os/cosmic-workspaces/files/8848030/with-less-logs.txt)

[with-less-logs_dash-to-panel_enabled.txt](https://github.com/pop-os/cosmic-workspaces/files/8848031/with-less-logs_dash-to-panel_enabled.txt)
[without-less-logs_dash-to-panel_enabled.txt](https://github.com/pop-os/cosmic-workspaces/files/8848033/without-less-logs_dash-to-panel_enabled.txt)

**Review by jackpot51 — APPROVED** [review]
